### ISSUE TITLE
NAN value in bond_order_params class

### ISSUE THREAD

**Issue by David-Zagaceta** [qzhu2017/PyXtal_ml#41]
```
run: 100%|####################################| 100/100 [03:53<00:00,  2.07s/it]

ML learning with KRR algorithm
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    runner.ml_train(algo=algorithm)
  File "/homes/davidz87/PyXtal_ml/pyxtal_ml/run.py", line 165, in ml_train
    pipeline=self.pipeline, params=self.level)
  File "/homes/davidz87/PyXtal_ml/pyxtal_ml/ml/ml_sklearn.py", line 94, in __init__
    self.ml()
  File "/homes/davidz87/PyXtal_ml/pyxtal_ml/ml/ml_sklearn.py", line 204, in ml
    best_estimator.fit(self.X_train, self.Y_train)
  File "/homes/davidz87/Python-3.6.5/lib/python3.6/site-packages/sklearn/model_selection/_search.py", line 722, in fit
    self._run_search(evaluate_candidates)
  File "/homes/davidz87/Python-3.6.5/lib/python3.6/site-packages/sklearn/model_selection/_search.py", line 1191, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "/homes/davidz87/Python-3.6.5/lib/python3.6/site-packages/sklearn/model_selection/_search.py", line 711, in evaluate_candidates
    cv.split(X, y, groups)))
  File "/homes/davidz87/Python-3.6.5/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 983, in __call__
    if self.dispatch_one_batch(iterator):
  File "/homes/davidz87/Python-3.6.5/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 825, in dispatch_one_batch
    self._dispatch(tasks)
  File "/homes/davidz87/Python-3.6.5/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 782, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/homes/davidz87/Python-3.6.5/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/homes/davidz87/Python-3.6.5/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 545, in __init__
    self.results = batch()
  File "/homes/davidz87/Python-3.6.5/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 261, in __call__
    for func, args, kwargs in self.items]
  File "/homes/davidz87/Python-3.6.5/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 261, in <listcomp>
    for func, args, kwargs in self.items]
  File "/homes/davidz87/Python-3.6.5/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 568, in _fit_and_score
    test_scores = _score(estimator, X_test, y_test, scorer, is_multimetric)
  File "/homes/davidz87/Python-3.6.5/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 605, in _score
    return _multimetric_score(estimator, X_test, y_test, scorer)
  File "/homes/davidz87/Python-3.6.5/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 635, in _multimetric_score
    score = scorer(estimator, X_test, y_test)
  File "/homes/davidz87/Python-3.6.5/lib/python3.6/site-packages/sklearn/metrics/scorer.py", line 228, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/homes/davidz87/Python-3.6.5/lib/python3.6/site-packages/sklearn/base.py", line 328, in score
    return r2_score(y, self.predict(X), sample_weight=sample_weight,
  File "/homes/davidz87/Python-3.6.5/lib/python3.6/site-packages/sklearn/kernel_ridge.py", line 193, in predict
    K = self._get_kernel(X, self.X_fit_)
  File "/homes/davidz87/Python-3.6.5/lib/python3.6/site-packages/sklearn/kernel_ridge.py", line 125, in _get_kernel
    filter_params=True, **params)
  File "/homes/davidz87/Python-3.6.5/lib/python3.6/site-packages/sklearn/metrics/pairwise.py", line 1559, in pairwise_kernels
    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)
  File "/homes/davidz87/Python-3.6.5/lib/python3.6/site-packages/sklearn/metrics/pairwise.py", line 1069, in _parallel_pairwise
    return func(X, Y, **kwds)
  File "/homes/davidz87/Python-3.6.5/lib/python3.6/site-packages/sklearn/metrics/pairwise.py", line 722, in linear_kernel
    X, Y = check_pairwise_arrays(X, Y)
  File "/homes/davidz87/Python-3.6.5/lib/python3.6/site-packages/sklearn/metrics/pairwise.py", line 111, in check_pairwise_arrays
    warn_on_dtype=warn_on_dtype, estimator=estimator)
  File "/homes/davidz87/Python-3.6.5/lib/python3.6/site-packages/sklearn/utils/validation.py", line 568, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/homes/davidz87/Python-3.6.5/lib/python3.6/site-packages/sklearn/utils/validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

I will investigate the source of these values tomorrow.  I think this may be coming from the odd numbered bond order parameters.

**Comment by David-Zagaceta** [comment]
I've ran other ML methods without the error that KRR is producing.  I think its an issue with the Kernel.
